### ISSUE TITLE
Bad IRecipe

### ISSUE THREAD

**Issue by purpleposeidon** [jaquadro/GardenCollection#13]
There's a custom IRecipe that creates oak logs. It lets you craft oak logs out of many incorrect items.

**Comment by jaquadro** [comment]
Can you give an example of the incorrect items?

**Comment by jaquadro** [comment]
I forgot that metadata values 0-16 would also resolve to vanilla types.  Recipes should be fixed now.  Please verify.

**Comment by purpleposeidon** [comment]
Yep, it's fixed.
