### ISSUE TITLE
Possible Minor Graphical issue with posts & Chains

### ISSUE THREAD

**Issue by InkDragon** [jaquadro/GardenCollection#14]
Not sure if this could be fixed, but when using a horizontal post and any chain they will not connect providing a small visual gap. 

https://www.dropbox.com/s/pjco0fax8fdamu4/Screenshot%202015-03-02%2001.52.47.png?dl=0

again it's a very minor thing

**Comment by jaquadro** [comment]
I need to register a new attach point for them.  Same for the lattice blocks I just added.  It should be true for all of my blocks that the chains attach at reasonable points.  For all other blocks, they'll do whatever they do.

**Comment by jaquadro** [comment]
This was fixed in the last round of bugfixes.
