### ISSUE TITLE
Botania Lense bore causing area crash

### ISSUE THREAD

**Issue by b0bst3r** [jaquadro/GardenCollection#18]
Using Botania Lense bores to cut oak trees grown on garden soil resulted in my base area not loading and the resulting crash.

http://pastebin.com/HgHecyPq

The issue I think is that the tree grew as oak posts not oak wood and the bottom block of the tree (which was cut) had to be replaced with a block using world edit before the area was loadable.

GardenStuff-1.7.10-1.5.6.jar
Botania r1.6-173.jar

**Comment by jaquadro** [comment]
Fixed in dev.  Should no longer be a problem when the next version is released.
