### ISSUE TITLE
Crash when updating to 1.6.5

### ISSUE THREAD

**Issue by utoc** [jaquadro/GardenCollection#31]
Hello!

I'm updating BBQSauce to the next release and ended up with a crash when updating GardenStuff from 1.6.3 to 1.6.5.  Reverting to 1.6.3 causes the symptoms to cease.

```Caused by: java.lang.ClassNotFoundException: com.InfinityRaider.AgriCraft.api.v1.ISoilContainer```

Full crashlog Here: http://pastebin.com/QPSHAAfY

This test version is running Agricraft 1.3.1 and FML 1448.  Full mod list located here: https://www.reddit.com/r/BBQSauce/wiki/modlist

**Comment by InfinityRaider** [comment]
Update Agricraft to 1.4

**Comment by utoc** [comment]
Ah!  Thanks for pointing that out.
