### ISSUE TITLE
Crash with AgriCraft

### ISSUE THREAD

**Issue by Havanacus** [jaquadro/GardenCollection#32]
Tested with only:
     Forge 10.13.4.1492
     AgriCraft-1.7.10-1.3.1
     GardenStuff-1.7.10-1.6.5

Game launches normally with one or the other, but crashes on launch with both.  Please let me know if this should be submitted to Agricraft's bugtracker instead.

Crash Log: http://pastebin.com/xvL43KsJ

**Comment by jaquadro** [comment]
Update Agricraft to the 1.4.x branch.

@InfinityRaider: I think the only way I can avoid crashing with earlier versions of AgriCraft present is to ship the parts of your API that I'm implementing.  I have been previously assured that with correctly configured package-info, third parties with outdated APIs won't override the primary provider.

**Comment by Havanacus** [comment]
I didn't realize there was a beta version of AgriCraft out. Thanks.

**Comment by InfinityRaider** [comment]
As long as you know what you're doing and don't break anything, I'm fine with it.
