### ISSUE TITLE
Cannot minetweak crop mutations with <GardenTrees:candelilla_seeds>

### ISSUE THREAD

**Issue by codewarrior0** [jaquadro/GardenCollection#42]
Minetweaker script:

```
val seedCactus = <AgriCraft:seedCactus>;
val seedPumpkin = <minecraft:pumpkin_seeds>;
val seedCandelilla = <GardenTrees:candelilla_seeds>;

SeedMutation.add(seedCandelilla, seedCactus, seedPumpkin);
```

Error reported by MT:

```
ERROR: Adding mutation with result 'Candelilla Seeds' failed. All 3 have to be of type ItemSeeds.
```

Candelilla Seeds [seems to inherit from ItemSeeds](https://github.com/jaquadro/GardenCollection/blob/master/src/com/jaquadro/minecraft/gardentrees/core/ModItems.java#L14), but it is [your own ItemSeeds class](https://github.com/jaquadro/GardenCollection/blob/master/src/com/jaquadro/minecraft/gardentrees/item/ItemSeeds.java) instead of `net.minecraft.item.ItemSeeds`.

This also seems to make it impossible to grow candelilla seeds on crop sticks.

**Comment by InfinityRaider** [comment]
Update AgriCraft

**Comment by codewarrior0** [comment]
```
1.4.6
-ADDED:  Support for Garden Stuff's candelilla crop
```

Will do!

**Comment by jaquadro** [comment]
@InfinityRaider would it be best practice to change my inheritance?  I'm not sure what the majority of mods do here.  I never thought to check.

**Comment by InfinityRaider** [comment]
No, ages ago, I used the ItemSeeds class to get all information I need, but because 80% of the modders are not using that class and instead creating their own one, I stepped away from that and created my own interface. That instanceof ItemSeeds check is a leftover from that time, which I cleaned up now.
