### ISSUE TITLE
Particle Crash, I think?

### ISSUE THREAD

**Issue by BevoLJ** [jaquadro/GardenCollection#5]
Hello,

We recently added Garden Stuff to our mod pack and a user had an odd issue when braking a spruce log fence with a TCon hatchet.  Looking at the crash I am guessing it is a particle effect that caused it. Was wondering if you might be able to take a look and hopefully point me in the right direction.

Crash Log: http://pastebin.com/K24wt1jr
Issue where user posted: https://github.com/BevoTechPack/BevoTechPack/issues/476

I am not sure if the particles are from your side or TCons, so if I need to speak to them will be happy to do so (if those are the issue).

**Comment by jaquadro** [comment]
I think this was fixed a while ago.  If it's not, please re-open the issue.  Thanks.
