### ISSUE TITLE
[1.12] Items shows up in every Creative Tab

### ISSUE THREAD

**Issue by ParaMotor** [jaquadro/GardenCollection#54]
The Items from Garden Stuff show up in every Creative Tab (even Vanilla Tabs), not only in the Garden Stuff Tab.

EDIT: Not all Items are affected as I've seen it now. Affected are: Iron Nugget, Iron/Gold Link, Wrought Iron Nugget/Ingot/Link, Candelilla and Wax. And these are always the same one.

Using:
forge-14.21.1.2412
GardenStuff1.12-2.0.0

**Comment by jaquadro** [comment]
Oh yeah.  I even knew about this but forgot to fix it before release :E

**Comment by jaquadro** [comment]
This should be fixed under Chameleon 4.1.3.
